name: Bun and Node.js Workflow

on:
  workflow_dispatch:

jobs:
  test-bun-alpine:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:1.2.13-alpine

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          
      - name: Install glibc
        run: |
          apk --no-cache add ca-certificates wget
          wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
          wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.34-r0/glibc-2.34-r0.apk
          apk add glibc-2.34-r0.apk

      - name: where is node
        run: which node

      - name: Display Node.js version
        run: node --version

      - name: Display npm version
        run: npm --version
