name: 1027 Error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update corepack
      run: sudo npm install -g corepack

    - name: Enable corepack
      run: corepack enable

    - name: Install Yarn (specific version)
      run: corepack prepare yarn@1.22.17 --activate

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test
