# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package


on:
  push

jobs:
  build:
    runs-on: windows-latest

    
    steps:
      - uses: actions/checkout@v3
      
      # - uses: priyagupta108/setup-node@PR-927
      
      - uses: actions/setup-node@v4
         
        with:
          node-version: 20
          
          
      - run: npm ci
      - run: npm test

      - name: "rate limit"
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit

 
