# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: priyagupta108/setup-node@PR-927
        with:
          node-version: 20
          architecture: arm64
      - run: npm ci
      - run: npm test

  # publish-npm:
  #   needs: build
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: priyagupta108/setup-node@PR-927
  #       with:
  #         node-version: 16
  #         architecture: arm64
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm publish --access=public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
